default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5

  development:
  encoding: unicode
  database: myapp_development
  pool: 5

development:
  <<: *default
  database: themeactiveadmin_development

test:
  <<: *default
  database: themeactiveadmin_test

production:
  <<: *default
  database: <%= ENV["DATABASE_URL"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
